=== devopslibrary/sample-adde-api/servers/.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "Server",
  "required": [
    "name",
    "owner",
    "contact",
    "lastUpdated",
    "datacenter",
    "purpose",
    "os",
    "firmware",
    "ip"
  ],
  "properties": {
    "name": {
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "pattern": "^(.*)$"
    },
    "owner": {
      "type": "string",
      "title": "The Owner Schema",
      "default": "",
      "pattern": "^(.*)$"
    },
    "contact": {
      "type": "string",
      "title": "The Contact Schema",
      "default": "",
      "pattern": "^(.*)$"
    },
    "lastUpdated": {
      "type": "string",
      "title": "The Lastupdated Schema",
      "default": "",
      "pattern": "^(.*)$"
    },
    "datacenter": {
      "type": "object",
      "title": "The Datacenter Schema",
      "required": ["$ref"],
      "properties": {
        "$ref": {
          "type": "string",
          "title": "The $ref Schema",
          "default": "",
          "pattern": "^(.*)$"
        }
      }
    },
    "purpose": {
      "type": "string",
      "title": "The Purpose Schema",
      "default": "",
      "pattern": "^(.*)$"
    },
    "os": {
      "type": "string",
      "title": "The Os Schema",
      "default": "",
      "pattern": "^(.*)$"
    },
    "firmware": {
      "type": "string",
      "title": "The Firmware Schema",
      "default": "",
      "pattern": "^(.*)$"
    },
    "ip": {
      "type": "string",
      "title": "The Ip Schema",
      "default": "",
      "pattern": "^(.*)$"
    }
  }
}

=== devopslibrary/sample-adde-api/servers/ind01prdc01.json
{
  "name": "ind01prdc01",
  "owner": "Infrastructure Team",
  "contact": "it@loremipsum.org",
  "lastUpdated": "2019-12-30T19:31:41Z",
  "datacenter": { "$ref": "../datacenters/ind01pr.json" },
  "purpose": "domainController",
  "os": "Windows Server 2016",
  "firmware": "12.04.a",
  "ip": "172.16.0.4"
}

=== devopslibrary/sample-adde-api/servers/san01drdc01.json
{
  "name": "san01drdc01",
  "owner": "Infrastructure Team",
  "contact": "it@loremipsum.org",
  "lastUpdated": "2019-12-30T19:31:41Z",
  "datacenter": { "$ref": "../datacenters/san01dr.json" },
  "purpose": "domainController",
  "os": "Windows Server 2016",
  "firmware": "12.04.a",
  "ip": "172.32.0.4"
}
